version: "3.9"

services:
  clonebot:
    image: ghcr.io/missemily2022/clonebot:new
    container_name: clonebot
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - UPDATES_CHANNEL=${UPDATES_CHANNEL}
      - OWNER_ID=${OWNER_ID}
      - DATABASE_URL=${DATABASE_URL}
      - PRESET=${PRESET}

    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
